version: '3.8'
services:
  app:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    image: market-app:monica
    container_name: market-app-monica
    restart: on-failure
    env_file:
      - .env
